# Isolate SDK variables: LLVMConfig.cmake can override the host MSVC runtime.
function(iris_link_llvm)
  find_package(LLVM REQUIRED CONFIG)
  if(LLVM_VERSION_MAJOR LESS 20 OR LLVM_VERSION_MAJOR GREATER 22)
    message(FATAL_ERROR "Iris requires LLVM 20-22; found ${LLVM_PACKAGE_VERSION}")
  endif()
  target_sources(iris PRIVATE src/llvm/llvm.cpp)
  target_include_directories(iris SYSTEM PRIVATE ${LLVM_INCLUDE_DIRS})
  if(TARGET LLVM)
    target_link_libraries(iris PRIVATE LLVM)
  elseif(TARGET LLVM-C)
    target_link_libraries(iris PRIVATE LLVM-C)
  else()
    message(FATAL_ERROR "Iris requires an exported LLVM or LLVM-C CMake target")
  endif()
  target_compile_definitions(iris PRIVATE IRIS_WITH_LLVM=1)
endfunction()
