# Isolate SDK variables: LLVMConfig.cmake can override the host MSVC runtime.
function(iris_link_llvm)
  find_package(LLVM REQUIRED CONFIG)
  if(LLVM_VERSION_MAJOR LESS 20)
    message(FATAL_ERROR "Iris requires LLVM 20 or newer; found ${LLVM_PACKAGE_VERSION}")
  elseif(LLVM_VERSION_MAJOR GREATER 23)
    message(WARNING "LLVM ${LLVM_PACKAGE_VERSION} is newer than the tested LLVM 20-23 range; continuing")
  endif()
  target_sources(iris PRIVATE src/llvm/llvm.cpp)
  target_include_directories(iris SYSTEM PRIVATE ${LLVM_INCLUDE_DIRS})
  if(IRIS_LLVM_STATIC)
    llvm_map_components_to_libnames(iris_llvm_libraries core orcjit passes nativecodegen)
    foreach(library IN LISTS iris_llvm_libraries)
      if(NOT TARGET ${library})
        message(FATAL_ERROR "IRIS_LLVM_STATIC requires the LLVM component ${library}")
      endif()
      get_target_property(library_type ${library} TYPE)
      if(NOT library_type STREQUAL "STATIC_LIBRARY")
        message(FATAL_ERROR "IRIS_LLVM_STATIC requires static LLVM components; ${library} is ${library_type}")
      endif()
    endforeach()
    target_link_libraries(iris PRIVATE ${iris_llvm_libraries})
    target_compile_definitions(iris PRIVATE LLVM_BUILD_STATIC)
  elseif(TARGET LLVM)
    target_link_libraries(iris PRIVATE LLVM)
  elseif(TARGET LLVM-C)
    target_link_libraries(iris PRIVATE LLVM-C)
  else()
    message(FATAL_ERROR "Iris requires an exported LLVM or LLVM-C CMake target")
  endif()
  target_compile_definitions(iris PRIVATE IRIS_WITH_LLVM=1)
endfunction()
